services:
  ze-erp-backend:
    container_name: ze-erp-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "7001:3000"
    networks:
      - ze-erp-net

  seed:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    env_file:
      - .env
    environment:
      - BASE_URL=http://ze-erp-backend:3000
    command: npm run seed
    profiles:
      - seed
    networks:
      - ze-erp-net

networks:
  ze-erp-net:
    external: true
