/**
 * Maps domain error codes → HTTP status (ADR-0002 §2.3 Error envelope). INFRASTRUCTURE/PRESENTATION
 * concern — the domain throws typed `DomainError`s and never imports Nest's HttpException; this table
 * is the single place that decides their HTTP status.
 */
import { HttpStatus } from '@nestjs/common';
import { DomainErrorCode } from '../../common/errors/domain-error';

export const DOMAIN_ERROR_STATUS: Record<DomainErrorCode, HttpStatus> = {
  [DomainErrorCode.VALIDATION]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.MISSING_DIMENSION]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.LEDGER_IMBALANCE]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.INVALID_LINE]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.PROJECT_CLOSED]: HttpStatus.CONFLICT,
  [DomainErrorCode.ALREADY_REVERSED]: HttpStatus.CONFLICT,
  [DomainErrorCode.CANNOT_REVERSE_REVERSAL]: HttpStatus.CONFLICT,
  [DomainErrorCode.TENANT_SCOPE_MISSING]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.CROSS_COMPANY_REFERENCE]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.DUPLICATE_CODE]: HttpStatus.CONFLICT,
  [DomainErrorCode.DUPLICATE_NAME]: HttpStatus.CONFLICT,
  [DomainErrorCode.IMMUTABLE_PROJECT_CODE]: HttpStatus.CONFLICT,
  [DomainErrorCode.INVALID_STATUS_TRANSITION]: HttpStatus.CONFLICT,
  [DomainErrorCode.REFERENCED_MASTER]: HttpStatus.CONFLICT,
  [DomainErrorCode.ACCOUNT_TYPE_MISMATCH]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.ACCOUNT_TYPE_IMMUTABLE]: HttpStatus.CONFLICT,
  [DomainErrorCode.BASE_UOM_IMMUTABLE]: HttpStatus.CONFLICT,
  [DomainErrorCode.CROSS_PROJECT_DIMENSION]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.SERIES_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [DomainErrorCode.NUMBERING_EXHAUSTED]: HttpStatus.CONFLICT,
  [DomainErrorCode.NEGATIVE_STOCK_BLOCKED]: HttpStatus.CONFLICT,
  [DomainErrorCode.NOT_BANK_CASH_ACCOUNT]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.MISSING_REQUIRED_DIMENSION]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.MISSING_CONTROL_PARTY]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.UNBALANCED_ENTRY]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.VOUCHER_POSTED_IMMUTABLE]: HttpStatus.CONFLICT,
  [DomainErrorCode.VOUCHER_NOT_POSTED]: HttpStatus.CONFLICT,
  [DomainErrorCode.OPENING_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [DomainErrorCode.OPENING_ACCOUNT_NOT_CONFIGURED]: HttpStatus.CONFLICT,
  [DomainErrorCode.DUPLICATE_IPC_SEQ_NO]: HttpStatus.CONFLICT,
  [DomainErrorCode.CURRENTLY_DUE_NEGATIVE]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.ADVANCE_EXCEEDS_REMAINING]: HttpStatus.CONFLICT,
  [DomainErrorCode.CERTIFIED_NOT_POSITIVE]: HttpStatus.BAD_REQUEST,
  [DomainErrorCode.SALES_ACCOUNT_NOT_CONFIGURED]: HttpStatus.CONFLICT,
  [DomainErrorCode.PERIOD_CLOSED]: HttpStatus.CONFLICT,
  [DomainErrorCode.NO_PERIOD_DEFINED]: HttpStatus.CONFLICT,
  [DomainErrorCode.PERIODS_ALREADY_EXIST]: HttpStatus.CONFLICT,
  [DomainErrorCode.PERIOD_OVERLAP]: HttpStatus.CONFLICT,
  [DomainErrorCode.PERIOD_ALREADY_CLOSED]: HttpStatus.CONFLICT,
  [DomainErrorCode.PERIOD_ALREADY_OPEN]: HttpStatus.CONFLICT,
  [DomainErrorCode.PERIOD_FY_LOCKED]: HttpStatus.CONFLICT,
  [DomainErrorCode.NO_PERIODS_FOR_FY]: HttpStatus.NOT_FOUND,
  [DomainErrorCode.FINANCIAL_YEAR_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [DomainErrorCode.CONFLICT]: HttpStatus.CONFLICT,
  [DomainErrorCode.OPTIMISTIC_LOCK_CONFLICT]: HttpStatus.CONFLICT,
  [DomainErrorCode.APPEND_ONLY_VIOLATION]: HttpStatus.CONFLICT,
  [DomainErrorCode.NOT_FOUND]: HttpStatus.NOT_FOUND,
  [DomainErrorCode.UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
  [DomainErrorCode.FORBIDDEN]: HttpStatus.FORBIDDEN,
};
